### ISSUE TITLE
Roadmap for v2.0

### ISSUE THREAD

**Issue by jelhan** [rwjblue/ember-cli-content-security-policy#100]
_Disclaimer: This is only a proposal as I'm not the maintainer of this repo._

As you might have noticed I'm working on an incremental refactoring of the configuration of this addon. It makes sense to ship all changes in one release to avoid unnecessary noice.

I would suggest that next release includes these features:

* [x] Move configuration to `ember-cli-content-security-policy` namespace, introduce an explicit `enabled` option and reword other options. (#92, #94)
* [x] Move configuration to `config/content-security-policy.js`. (#30, #97, #104)
* [x] Policy object should be replaced by application configuration not merged. (#99, #101)

There are some pending feature requests that could be implemented having sensitive defaults without introducing a breaking change if shiped together with configuration changes:

* [x] Add an assertion to fail tests if CSP is violated. (#91)
* [x] Add CSP header in FastBoot if addon is enabled and `delivery` includes `header`. (#113)

I suggest shipping all of them with the next release.

Also there are some bugs/regressions introduced by refactoring that must be fixed before release:

* [x] CLI command is not using refactored configuration. (#98, #103)
* [x] Runtime configuration should not be injected if not needed (#116, #121)
* [x] Throws in FastBoot if disabled or delivery does not include header (#117, #118)
* [x] Ensure consistent test results by always using test environment for CSP affecting tests (#119, #122)

Steps to be done after release:

* [ ] Update Ember CLI docs for [Content Security Policy](https://cli.emberjs.com/release/basic-use/deploying/#contentsecuritypolicy) (https://github.com/ember-learn/cli-guides/pull/146)

This would be a great foundation for https://github.com/jelhan/ember-style-modifier/issues/11.

**Comment by sandstrom** [comment]
Sounds good! Ping me or rwjblue if you want us to review or merge something. 

You can also ask rwjblue for repo access, perhaps he can give you. However, even if you'd have repo access I still think it would be vice to have another pair of eyes look through code before it's merged.

**Comment by rwjblue** [comment]
OK, just merged #101 which I think ticks a couple of the boxes above.

**Comment by jelhan** [comment]
I think this will be a `v2.0` release cause of #87. It has upgraded Ember CLI and therefore requires a newer node version. I think we should support legacy configuration nevertheless but make sure that we name the correct until version in deprecation message: https://github.com/rwjblue/ember-cli-content-security-policy/blob/9cd237f6e18c141f9a8540dbf91368dd3261ef72/index.js#L257-L264

**Comment by rwjblue** [comment]
Sounds good, sorry for making things a bit more difficult here @jelhan

**Comment by rwjblue** [comment]
OK, how are things looking now @jelhan? I _think_ the only checklist item left is:

>  Add CSP header in FastBoot if addon is enabled and delivery includes header.

Is that right?

**Comment by jelhan** [comment]
> OK, how are things looking now @jelhan? I _think_ the only checklist item left is:
> 
> > Add CSP header in FastBoot if addon is enabled and delivery includes header.
> 
> Is that right?

Yes.

We might also need some more testing on real world applications to avoid regressions. It was a major refactoring and the test coverage isn't that high. Maybe a beta release would be a good idea.

**Comment by rwjblue** [comment]
> Maybe a beta release would be a good idea.

Ya, totally makes sense.

**Comment by jelhan** [comment]
We should also update the Ember CLI docs which includes a section on Content Security Policy: https://cli.emberjs.com/release/basic-use/deploying/#contentsecuritypolicy It seems to miss the install step though.

**Comment by rwjblue** [comment]
> We should also update the Ember CLI docs which includes a section on Content Security Policy: cli.emberjs.com/release/basic-use/deploying/#contentsecuritypolicy It seems to miss the install step though.

Ya, probably ignores the install step because it was originally authored when the addon was installed by default?

**Comment by jelhan** [comment]
Added #116 as another release blocker. Have a look at https://github.com/rwjblue/ember-cli-content-security-policy/pull/113#discussion_r332152371 for background.

**Comment by jelhan** [comment]
Sorry for the long delay here. Created three merge requests the last days: #120, #121, #122 I think we are ready to do a first release candidate as soon as these ones are merged.

**Comment by jelhan** [comment]
@rwjblue Everything should be ready for a `2.0.0-rc.0` release. As far as I know you are the only one who can do releases, aren't you?

**Comment by rwjblue** [comment]
FYI - Added @jelhan to npm...

**Comment by pragatheeswaranshf** [comment]
Any tentative date for this release? @jelhan

**Comment by jelhan** [comment]
> Any tentative date for this release? @jelhan

Hopefully this week. Need to get #134 merged in before. Thanks to @reibad we were able to fix some more bugs before first release candidate.

**Comment by jelhan** [comment]
Just released the first release candidate for upcoming 2.x: `v2.0.0-0`

**Comment by jelhan** [comment]
During the beta period I noticed some problems related to developer experience, which I would like to fix before the first stable release. I created a milestone to track the work needed to be done before a stable v2 release: https://github.com/rwjblue/ember-cli-content-security-policy/milestone/1 PRs are welcome as always. :smile:

**Comment by sandstrom** [comment]
@jelhan I personally don't think any of the three issues listed under that milestone is a blocker for a v2 release.

**Comment by jelhan** [comment]
I'm very sorry that it takes so long until getting a stable release out.

I agree that they aren't strictly necessary cause even without it's an improvement compared to latest v1 release. But I would consider #152 a blocker. Just added it to the milestone.

To be honest I would prefer rather to wait a little bit longer and fix everything before doing a stable v2 release rather than doing the release after #152. Mostly cause it has already been such a long time. I would like to combine a stable release with some marketing. And therefore providing a good developer experience is required.

I was rewriting the fragile test suite based on ember-cli-addon-tests in the last months. The unstable and slow tests slowed down development a lot. I hope that I land the changes within this week. Everything working locally. Just need to polish it a little bit.

I expect to be able to finish the other open tasks in v2 milestone soon after. I hope that we can do a stable v2 release containing all of them within this month.

**Comment by jelhan** [comment]
No new bugs were reported. Releasing `v2.0.0-5` as [`v2.0.0`](https://github.com/rwjblue/ember-cli-content-security-policy/releases/tag/v2.0.0). After way too long time this issue can be closed.
